//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace cast.core {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICastParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CastParserBaseListener : ICastParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslation_unit([NotNull] CastParser.Translation_unitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslation_unit([NotNull] CastParser.Translation_unitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.external_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExternal_declaration([NotNull] CastParser.External_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.external_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExternal_declaration([NotNull] CastParser.External_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.declaration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration_statement([NotNull] CastParser.Declaration_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.declaration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration_statement([NotNull] CastParser.Declaration_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_statement([NotNull] CastParser.Expression_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.expression_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_statement([NotNull] CastParser.Expression_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.selection_rest_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection_rest_statement([NotNull] CastParser.Selection_rest_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.selection_rest_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection_rest_statement([NotNull] CastParser.Selection_rest_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection_statement([NotNull] CastParser.Selection_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.selection_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection_statement([NotNull] CastParser.Selection_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] CastParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] CastParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.switch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_statement([NotNull] CastParser.Switch_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.switch_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_statement([NotNull] CastParser.Switch_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.case_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCase_label([NotNull] CastParser.Case_labelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.case_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCase_label([NotNull] CastParser.Case_labelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIteration_statement([NotNull] CastParser.Iteration_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.iteration_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIteration_statement([NotNull] CastParser.Iteration_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.for_init_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_init_statement([NotNull] CastParser.For_init_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.for_init_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_init_statement([NotNull] CastParser.For_init_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.for_rest_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_rest_statement([NotNull] CastParser.For_rest_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.for_rest_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_rest_statement([NotNull] CastParser.For_rest_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJump_statement([NotNull] CastParser.Jump_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.jump_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJump_statement([NotNull] CastParser.Jump_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.simple_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimple_statement([NotNull] CastParser.Simple_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.simple_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimple_statement([NotNull] CastParser.Simple_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement_no_new_scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_no_new_scope([NotNull] CastParser.Statement_no_new_scopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement_no_new_scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_no_new_scope([NotNull] CastParser.Statement_no_new_scopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_statement([NotNull] CastParser.Compound_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.compound_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_statement([NotNull] CastParser.Compound_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.compound_statement_no_new_scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompound_statement_no_new_scope([NotNull] CastParser.Compound_statement_no_new_scopeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.compound_statement_no_new_scope"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompound_statement_no_new_scope([NotNull] CastParser.Compound_statement_no_new_scopeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CastParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CastParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement_list([NotNull] CastParser.Statement_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement_list([NotNull] CastParser.Statement_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_definition([NotNull] CastParser.Function_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_definition([NotNull] CastParser.Function_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.variable_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable_identifier([NotNull] CastParser.Variable_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.variable_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable_identifier([NotNull] CastParser.Variable_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call([NotNull] CastParser.Function_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call([NotNull] CastParser.Function_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.field_selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_selection([NotNull] CastParser.Field_selectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.field_selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_selection([NotNull] CastParser.Field_selectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_identifier([NotNull] CastParser.Function_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_identifier([NotNull] CastParser.Function_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.dimension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDimension([NotNull] CastParser.DimensionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.dimension"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDimension([NotNull] CastParser.DimensionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.array_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_specifier([NotNull] CastParser.Array_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.array_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_specifier([NotNull] CastParser.Array_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.space_definition_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpace_definition_parameters([NotNull] CastParser.Space_definition_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.space_definition_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpace_definition_parameters([NotNull] CastParser.Space_definition_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.space_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpace_specifier([NotNull] CastParser.Space_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.space_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpace_specifier([NotNull] CastParser.Space_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_specifier([NotNull] CastParser.Type_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_specifier([NotNull] CastParser.Type_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expression([NotNull] CastParser.Primary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.primary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expression([NotNull] CastParser.Primary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expression([NotNull] CastParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.postfix_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expression([NotNull] CastParser.Postfix_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.integer_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInteger_expression([NotNull] CastParser.Integer_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.integer_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInteger_expression([NotNull] CastParser.Integer_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_call_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_call_parameters([NotNull] CastParser.Function_call_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_call_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_call_parameters([NotNull] CastParser.Function_call_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CastParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CastParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expression([NotNull] CastParser.Unary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.unary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expression([NotNull] CastParser.Unary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_operator([NotNull] CastParser.Unary_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.unary_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_operator([NotNull] CastParser.Unary_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_expression([NotNull] CastParser.Constant_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_expression([NotNull] CastParser.Constant_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_expression([NotNull] CastParser.Assignment_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.assignment_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_expression([NotNull] CastParser.Assignment_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.binary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinary_expression([NotNull] CastParser.Binary_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.binary_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinary_expression([NotNull] CastParser.Binary_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_operator([NotNull] CastParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.assignment_operator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_operator([NotNull] CastParser.Assignment_operatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] CastParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] CastParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.identifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier_list([NotNull] CastParser.Identifier_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.identifier_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier_list([NotNull] CastParser.Identifier_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_prototype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_prototype([NotNull] CastParser.Function_prototypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_prototype"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_prototype([NotNull] CastParser.Function_prototypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunction_parameters([NotNull] CastParser.Function_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunction_parameters([NotNull] CastParser.Function_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_declarator([NotNull] CastParser.Parameter_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_declarator([NotNull] CastParser.Parameter_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_declaration([NotNull] CastParser.Parameter_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_declaration([NotNull] CastParser.Parameter_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_type_specifier([NotNull] CastParser.Parameter_type_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_type_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_type_specifier([NotNull] CastParser.Parameter_type_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_qualifier([NotNull] CastParser.Type_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_qualifier([NotNull] CastParser.Type_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer_list([NotNull] CastParser.Initializer_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.initializer_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer_list([NotNull] CastParser.Initializer_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInitializer([NotNull] CastParser.InitializerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.initializer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInitializer([NotNull] CastParser.InitializerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.init_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit_declarator_list([NotNull] CastParser.Init_declarator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.init_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit_declarator_list([NotNull] CastParser.Init_declarator_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.single_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_declaration([NotNull] CastParser.Single_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.single_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_declaration([NotNull] CastParser.Single_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.typeless_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeless_declaration([NotNull] CastParser.Typeless_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.typeless_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeless_declaration([NotNull] CastParser.Typeless_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.fully_specified_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFully_specified_type([NotNull] CastParser.Fully_specified_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.fully_specified_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFully_specified_type([NotNull] CastParser.Fully_specified_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.single_type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_type_qualifier([NotNull] CastParser.Single_type_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.single_type_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_type_qualifier([NotNull] CastParser.Single_type_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.precise_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecise_qualifier([NotNull] CastParser.Precise_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.precise_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecise_qualifier([NotNull] CastParser.Precise_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.precision_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrecision_qualifier([NotNull] CastParser.Precision_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.precision_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrecision_qualifier([NotNull] CastParser.Precision_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.storage_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStorage_qualifier([NotNull] CastParser.Storage_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.storage_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStorage_qualifier([NotNull] CastParser.Storage_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.invariant_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInvariant_qualifier([NotNull] CastParser.Invariant_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.invariant_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInvariant_qualifier([NotNull] CastParser.Invariant_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.interpolation_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterpolation_qualifier([NotNull] CastParser.Interpolation_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.interpolation_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterpolation_qualifier([NotNull] CastParser.Interpolation_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier_id_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayout_qualifier_id_list([NotNull] CastParser.Layout_qualifier_id_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier_id_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayout_qualifier_id_list([NotNull] CastParser.Layout_qualifier_id_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayout_qualifier_id([NotNull] CastParser.Layout_qualifier_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayout_qualifier_id([NotNull] CastParser.Layout_qualifier_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLayout_qualifier([NotNull] CastParser.Layout_qualifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLayout_qualifier([NotNull] CastParser.Layout_qualifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declaration([NotNull] CastParser.Struct_declarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declaration([NotNull] CastParser.Struct_declarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declaration_list([NotNull] CastParser.Struct_declaration_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declaration_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declaration_list([NotNull] CastParser.Struct_declaration_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declarator_list([NotNull] CastParser.Struct_declarator_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declarator_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declarator_list([NotNull] CastParser.Struct_declarator_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_declarator([NotNull] CastParser.Struct_declaratorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declarator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_declarator([NotNull] CastParser.Struct_declaratorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_specifier([NotNull] CastParser.Struct_specifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_specifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_specifier([NotNull] CastParser.Struct_specifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_name([NotNull] CastParser.Type_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_name([NotNull] CastParser.Type_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_specifier_nonarray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_specifier_nonarray([NotNull] CastParser.Type_specifier_nonarrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_specifier_nonarray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_specifier_nonarray([NotNull] CastParser.Type_specifier_nonarrayContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace cast.core
