version: '3.8'

services:
  backend:
    build: 
      context: ./cast.api
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      # Verlinkt deinen lokalen Ordner in den Nginx-Ordner (ro = read-only)
      - ./cast.frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped