//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastPreParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace cast.core {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CastPreParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICastPreParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslation_unit([NotNull] CastPreParser.Translation_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslation_unit([NotNull] CastPreParser.Translation_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.compiler_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompiler_directive([NotNull] CastPreParser.Compiler_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.compiler_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompiler_directive([NotNull] CastPreParser.Compiler_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.behavior"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBehavior([NotNull] CastPreParser.BehaviorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.behavior"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBehavior([NotNull] CastPreParser.BehaviorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_expression([NotNull] CastPreParser.Constant_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_expression([NotNull] CastPreParser.Constant_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.define_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefine_directive([NotNull] CastPreParser.Define_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.define_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefine_directive([NotNull] CastPreParser.Define_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.elif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElif_directive([NotNull] CastPreParser.Elif_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.elif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElif_directive([NotNull] CastPreParser.Elif_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.else_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElse_directive([NotNull] CastPreParser.Else_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.else_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElse_directive([NotNull] CastPreParser.Else_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.endif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndif_directive([NotNull] CastPreParser.Endif_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.endif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndif_directive([NotNull] CastPreParser.Endif_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.error_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterError_directive([NotNull] CastPreParser.Error_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.error_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitError_directive([NotNull] CastPreParser.Error_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterError_message([NotNull] CastPreParser.Error_messageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitError_message([NotNull] CastPreParser.Error_messageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.extension_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_directive([NotNull] CastPreParser.Extension_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.extension_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_directive([NotNull] CastPreParser.Extension_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.extension_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExtension_name([NotNull] CastPreParser.Extension_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.extension_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExtension_name([NotNull] CastPreParser.Extension_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.group_of_lines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup_of_lines([NotNull] CastPreParser.Group_of_linesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.group_of_lines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup_of_lines([NotNull] CastPreParser.Group_of_linesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.if_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_directive([NotNull] CastPreParser.If_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.if_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_directive([NotNull] CastPreParser.If_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.ifdef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfdef_directive([NotNull] CastPreParser.Ifdef_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.ifdef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfdef_directive([NotNull] CastPreParser.Ifdef_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.ifndef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfndef_directive([NotNull] CastPreParser.Ifndef_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.ifndef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfndef_directive([NotNull] CastPreParser.Ifndef_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.line_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_directive([NotNull] CastPreParser.Line_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.line_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_directive([NotNull] CastPreParser.Line_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.line_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine_expression([NotNull] CastPreParser.Line_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.line_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine_expression([NotNull] CastPreParser.Line_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_esc_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacro_esc_newline([NotNull] CastPreParser.Macro_esc_newlineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_esc_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacro_esc_newline([NotNull] CastPreParser.Macro_esc_newlineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacro_identifier([NotNull] CastPreParser.Macro_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacro_identifier([NotNull] CastPreParser.Macro_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacro_name([NotNull] CastPreParser.Macro_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacro_name([NotNull] CastPreParser.Macro_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacro_text([NotNull] CastPreParser.Macro_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacro_text([NotNull] CastPreParser.Macro_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_text_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMacro_text_([NotNull] CastPreParser.Macro_text_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_text_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMacro_text_([NotNull] CastPreParser.Macro_text_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] CastPreParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] CastPreParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOff([NotNull] CastPreParser.OffContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOff([NotNull] CastPreParser.OffContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.on"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOn([NotNull] CastPreParser.OnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.on"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOn([NotNull] CastPreParser.OnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragma_debug([NotNull] CastPreParser.Pragma_debugContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragma_debug([NotNull] CastPreParser.Pragma_debugContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragma_directive([NotNull] CastPreParser.Pragma_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragma_directive([NotNull] CastPreParser.Pragma_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_optimize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPragma_optimize([NotNull] CastPreParser.Pragma_optimizeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_optimize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPragma_optimize([NotNull] CastPreParser.Pragma_optimizeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProfile([NotNull] CastPreParser.ProfileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProfile([NotNull] CastPreParser.ProfileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.program_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram_text([NotNull] CastPreParser.Program_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.program_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram_text([NotNull] CastPreParser.Program_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.stdgl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStdgl([NotNull] CastPreParser.StdglContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.stdgl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStdgl([NotNull] CastPreParser.StdglContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.undef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUndef_directive([NotNull] CastPreParser.Undef_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.undef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUndef_directive([NotNull] CastPreParser.Undef_directiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.version_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVersion_directive([NotNull] CastPreParser.Version_directiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.version_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVersion_directive([NotNull] CastPreParser.Version_directiveContext context);
}
} // namespace cast.core
