//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace cast.core {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CastParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICastParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslation_unit([NotNull] CastParser.Translation_unitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslation_unit([NotNull] CastParser.Translation_unitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable_identifier([NotNull] CastParser.Variable_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable_identifier([NotNull] CastParser.Variable_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expression([NotNull] CastParser.Primary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expression([NotNull] CastParser.Primary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_expression([NotNull] CastParser.Postfix_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_expression([NotNull] CastParser.Postfix_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.field_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_selection([NotNull] CastParser.Field_selectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.field_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_selection([NotNull] CastParser.Field_selectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.integer_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInteger_expression([NotNull] CastParser.Integer_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.integer_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInteger_expression([NotNull] CastParser.Integer_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call([NotNull] CastParser.Function_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call([NotNull] CastParser.Function_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_identifier([NotNull] CastParser.Function_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_identifier([NotNull] CastParser.Function_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_call_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_call_parameters([NotNull] CastParser.Function_call_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_call_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_call_parameters([NotNull] CastParser.Function_call_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expression([NotNull] CastParser.Unary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expression([NotNull] CastParser.Unary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_operator([NotNull] CastParser.Unary_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_operator([NotNull] CastParser.Unary_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_expression([NotNull] CastParser.Assignment_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_expression([NotNull] CastParser.Assignment_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment_operator([NotNull] CastParser.Assignment_operatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment_operator([NotNull] CastParser.Assignment_operatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinary_expression([NotNull] CastParser.Binary_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinary_expression([NotNull] CastParser.Binary_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CastParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CastParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant_expression([NotNull] CastParser.Constant_expressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant_expression([NotNull] CastParser.Constant_expressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CastParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CastParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier_list([NotNull] CastParser.Identifier_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier_list([NotNull] CastParser.Identifier_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_prototype([NotNull] CastParser.Function_prototypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_prototype([NotNull] CastParser.Function_prototypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_parameters([NotNull] CastParser.Function_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_parameters([NotNull] CastParser.Function_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declarator([NotNull] CastParser.Parameter_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declarator([NotNull] CastParser.Parameter_declaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_declaration([NotNull] CastParser.Parameter_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_declaration([NotNull] CastParser.Parameter_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.parameter_type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_type_specifier([NotNull] CastParser.Parameter_type_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.parameter_type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_type_specifier([NotNull] CastParser.Parameter_type_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInit_declarator_list([NotNull] CastParser.Init_declarator_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInit_declarator_list([NotNull] CastParser.Init_declarator_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.single_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_declaration([NotNull] CastParser.Single_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.single_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_declaration([NotNull] CastParser.Single_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.typeless_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeless_declaration([NotNull] CastParser.Typeless_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.typeless_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeless_declaration([NotNull] CastParser.Typeless_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.fully_specified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFully_specified_type([NotNull] CastParser.Fully_specified_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.fully_specified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFully_specified_type([NotNull] CastParser.Fully_specified_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.invariant_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInvariant_qualifier([NotNull] CastParser.Invariant_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.invariant_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInvariant_qualifier([NotNull] CastParser.Invariant_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.interpolation_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterpolation_qualifier([NotNull] CastParser.Interpolation_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.interpolation_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterpolation_qualifier([NotNull] CastParser.Interpolation_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayout_qualifier([NotNull] CastParser.Layout_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayout_qualifier([NotNull] CastParser.Layout_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayout_qualifier_id_list([NotNull] CastParser.Layout_qualifier_id_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayout_qualifier_id_list([NotNull] CastParser.Layout_qualifier_id_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.layout_qualifier_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLayout_qualifier_id([NotNull] CastParser.Layout_qualifier_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.layout_qualifier_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLayout_qualifier_id([NotNull] CastParser.Layout_qualifier_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.precise_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecise_qualifier([NotNull] CastParser.Precise_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.precise_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecise_qualifier([NotNull] CastParser.Precise_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_qualifier([NotNull] CastParser.Type_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_qualifier([NotNull] CastParser.Type_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.single_type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSingle_type_qualifier([NotNull] CastParser.Single_type_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.single_type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSingle_type_qualifier([NotNull] CastParser.Single_type_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.storage_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorage_qualifier([NotNull] CastParser.Storage_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.storage_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorage_qualifier([NotNull] CastParser.Storage_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name_list([NotNull] CastParser.Type_name_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name_list([NotNull] CastParser.Type_name_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_name([NotNull] CastParser.Type_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_name([NotNull] CastParser.Type_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_specifier([NotNull] CastParser.Type_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_specifier([NotNull] CastParser.Type_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_specifier([NotNull] CastParser.Array_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_specifier([NotNull] CastParser.Array_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimension([NotNull] CastParser.DimensionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimension([NotNull] CastParser.DimensionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.type_specifier_nonarray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_specifier_nonarray([NotNull] CastParser.Type_specifier_nonarrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.type_specifier_nonarray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_specifier_nonarray([NotNull] CastParser.Type_specifier_nonarrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.precision_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrecision_qualifier([NotNull] CastParser.Precision_qualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.precision_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrecision_qualifier([NotNull] CastParser.Precision_qualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_specifier([NotNull] CastParser.Struct_specifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_specifier([NotNull] CastParser.Struct_specifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declaration_list([NotNull] CastParser.Struct_declaration_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declaration_list([NotNull] CastParser.Struct_declaration_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declaration([NotNull] CastParser.Struct_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declaration([NotNull] CastParser.Struct_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declarator_list([NotNull] CastParser.Struct_declarator_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declarator_list([NotNull] CastParser.Struct_declarator_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_declarator([NotNull] CastParser.Struct_declaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_declarator([NotNull] CastParser.Struct_declaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] CastParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] CastParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer_list([NotNull] CastParser.Initializer_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer_list([NotNull] CastParser.Initializer_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.declaration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration_statement([NotNull] CastParser.Declaration_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.declaration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration_statement([NotNull] CastParser.Declaration_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CastParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CastParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.simple_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimple_statement([NotNull] CastParser.Simple_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.simple_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimple_statement([NotNull] CastParser.Simple_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_statement([NotNull] CastParser.Compound_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_statement([NotNull] CastParser.Compound_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_no_new_scope([NotNull] CastParser.Statement_no_new_scopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_no_new_scope([NotNull] CastParser.Statement_no_new_scopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.compound_statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompound_statement_no_new_scope([NotNull] CastParser.Compound_statement_no_new_scopeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.compound_statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompound_statement_no_new_scope([NotNull] CastParser.Compound_statement_no_new_scopeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_list([NotNull] CastParser.Statement_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_list([NotNull] CastParser.Statement_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_statement([NotNull] CastParser.Expression_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_statement([NotNull] CastParser.Expression_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection_statement([NotNull] CastParser.Selection_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection_statement([NotNull] CastParser.Selection_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.selection_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection_rest_statement([NotNull] CastParser.Selection_rest_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.selection_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection_rest_statement([NotNull] CastParser.Selection_rest_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] CastParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] CastParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_statement([NotNull] CastParser.Switch_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_statement([NotNull] CastParser.Switch_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCase_label([NotNull] CastParser.Case_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCase_label([NotNull] CastParser.Case_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIteration_statement([NotNull] CastParser.Iteration_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIteration_statement([NotNull] CastParser.Iteration_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.for_init_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_init_statement([NotNull] CastParser.For_init_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.for_init_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_init_statement([NotNull] CastParser.For_init_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.for_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_rest_statement([NotNull] CastParser.For_rest_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.for_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_rest_statement([NotNull] CastParser.For_rest_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJump_statement([NotNull] CastParser.Jump_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJump_statement([NotNull] CastParser.Jump_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternal_declaration([NotNull] CastParser.External_declarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternal_declaration([NotNull] CastParser.External_declarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunction_definition([NotNull] CastParser.Function_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunction_definition([NotNull] CastParser.Function_definitionContext context);
}
} // namespace cast.core
