//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastPreParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace cast.core {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CastPreParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICastPreParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] CastPreParser.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.compiler_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompiler_directive([NotNull] CastPreParser.Compiler_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.behavior"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBehavior([NotNull] CastPreParser.BehaviorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] CastPreParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.define_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefine_directive([NotNull] CastPreParser.Define_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.elif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElif_directive([NotNull] CastPreParser.Elif_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.else_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElse_directive([NotNull] CastPreParser.Else_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.endif_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndif_directive([NotNull] CastPreParser.Endif_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.error_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_directive([NotNull] CastPreParser.Error_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_message([NotNull] CastPreParser.Error_messageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.extension_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_directive([NotNull] CastPreParser.Extension_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.extension_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExtension_name([NotNull] CastPreParser.Extension_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.group_of_lines"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_of_lines([NotNull] CastPreParser.Group_of_linesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.if_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_directive([NotNull] CastPreParser.If_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.ifdef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfdef_directive([NotNull] CastPreParser.Ifdef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.ifndef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfndef_directive([NotNull] CastPreParser.Ifndef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.line_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_directive([NotNull] CastPreParser.Line_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.line_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine_expression([NotNull] CastPreParser.Line_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.macro_esc_newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_esc_newline([NotNull] CastPreParser.Macro_esc_newlineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.macro_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_identifier([NotNull] CastPreParser.Macro_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.macro_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_name([NotNull] CastPreParser.Macro_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.macro_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_text([NotNull] CastPreParser.Macro_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.macro_text_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMacro_text_([NotNull] CastPreParser.Macro_text_Context context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber([NotNull] CastPreParser.NumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.off"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOff([NotNull] CastPreParser.OffContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.on"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOn([NotNull] CastPreParser.OnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.pragma_debug"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_debug([NotNull] CastPreParser.Pragma_debugContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.pragma_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_directive([NotNull] CastPreParser.Pragma_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.pragma_optimize"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPragma_optimize([NotNull] CastPreParser.Pragma_optimizeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.profile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProfile([NotNull] CastPreParser.ProfileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.program_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram_text([NotNull] CastPreParser.Program_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.stdgl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStdgl([NotNull] CastPreParser.StdglContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.undef_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUndef_directive([NotNull] CastPreParser.Undef_directiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastPreParser.version_directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVersion_directive([NotNull] CastPreParser.Version_directiveContext context);
}
} // namespace cast.core
