//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastPreParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Cast.Compiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICastPreParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CastPreParserBaseListener : ICastPreParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTranslation_unit([NotNull] CastPreParser.Translation_unitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.translation_unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTranslation_unit([NotNull] CastPreParser.Translation_unitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.compiler_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompiler_directive([NotNull] CastPreParser.Compiler_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.compiler_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompiler_directive([NotNull] CastPreParser.Compiler_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBehavior([NotNull] CastPreParser.BehaviorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.behavior"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBehavior([NotNull] CastPreParser.BehaviorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant_expression([NotNull] CastPreParser.Constant_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.constant_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant_expression([NotNull] CastPreParser.Constant_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.define_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefine_directive([NotNull] CastPreParser.Define_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.define_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefine_directive([NotNull] CastPreParser.Define_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.elif_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElif_directive([NotNull] CastPreParser.Elif_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.elif_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElif_directive([NotNull] CastPreParser.Elif_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.else_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElse_directive([NotNull] CastPreParser.Else_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.else_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElse_directive([NotNull] CastPreParser.Else_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.endif_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndif_directive([NotNull] CastPreParser.Endif_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.endif_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndif_directive([NotNull] CastPreParser.Endif_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.error_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError_directive([NotNull] CastPreParser.Error_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.error_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError_directive([NotNull] CastPreParser.Error_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.error_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterError_message([NotNull] CastPreParser.Error_messageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.error_message"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitError_message([NotNull] CastPreParser.Error_messageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.extension_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtension_directive([NotNull] CastPreParser.Extension_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.extension_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtension_directive([NotNull] CastPreParser.Extension_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.extension_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExtension_name([NotNull] CastPreParser.Extension_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.extension_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExtension_name([NotNull] CastPreParser.Extension_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.group_of_lines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup_of_lines([NotNull] CastPreParser.Group_of_linesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.group_of_lines"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup_of_lines([NotNull] CastPreParser.Group_of_linesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.if_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_directive([NotNull] CastPreParser.If_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.if_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_directive([NotNull] CastPreParser.If_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.ifdef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfdef_directive([NotNull] CastPreParser.Ifdef_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.ifdef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfdef_directive([NotNull] CastPreParser.Ifdef_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.ifndef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfndef_directive([NotNull] CastPreParser.Ifndef_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.ifndef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfndef_directive([NotNull] CastPreParser.Ifndef_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.line_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_directive([NotNull] CastPreParser.Line_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.line_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_directive([NotNull] CastPreParser.Line_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.line_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLine_expression([NotNull] CastPreParser.Line_expressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.line_expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLine_expression([NotNull] CastPreParser.Line_expressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_esc_newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_esc_newline([NotNull] CastPreParser.Macro_esc_newlineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_esc_newline"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_esc_newline([NotNull] CastPreParser.Macro_esc_newlineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_identifier([NotNull] CastPreParser.Macro_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_identifier([NotNull] CastPreParser.Macro_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_name([NotNull] CastPreParser.Macro_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_name([NotNull] CastPreParser.Macro_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_text([NotNull] CastPreParser.Macro_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_text([NotNull] CastPreParser.Macro_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.macro_text_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMacro_text_([NotNull] CastPreParser.Macro_text_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.macro_text_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMacro_text_([NotNull] CastPreParser.Macro_text_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] CastPreParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] CastPreParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.off"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOff([NotNull] CastPreParser.OffContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.off"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOff([NotNull] CastPreParser.OffContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.on"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOn([NotNull] CastPreParser.OnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.on"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOn([NotNull] CastPreParser.OnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_debug"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_debug([NotNull] CastPreParser.Pragma_debugContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_debug"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_debug([NotNull] CastPreParser.Pragma_debugContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_directive([NotNull] CastPreParser.Pragma_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_directive([NotNull] CastPreParser.Pragma_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.pragma_optimize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPragma_optimize([NotNull] CastPreParser.Pragma_optimizeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.pragma_optimize"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPragma_optimize([NotNull] CastPreParser.Pragma_optimizeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.profile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProfile([NotNull] CastPreParser.ProfileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.profile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProfile([NotNull] CastPreParser.ProfileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.program_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram_text([NotNull] CastPreParser.Program_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.program_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram_text([NotNull] CastPreParser.Program_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.stdgl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStdgl([NotNull] CastPreParser.StdglContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.stdgl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStdgl([NotNull] CastPreParser.StdglContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.undef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUndef_directive([NotNull] CastPreParser.Undef_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.undef_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUndef_directive([NotNull] CastPreParser.Undef_directiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CastPreParser.version_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVersion_directive([NotNull] CastPreParser.Version_directiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CastPreParser.version_directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVersion_directive([NotNull] CastPreParser.Version_directiveContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Cast.Compiler
