//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CastParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Cast.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CastParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ICastParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] CastParser.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_identifier([NotNull] CastParser.Variable_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] CastParser.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_expression([NotNull] CastParser.Postfix_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.field_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_selection([NotNull] CastParser.Field_selectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.integer_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger_expression([NotNull] CastParser.Integer_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] CastParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_identifier([NotNull] CastParser.Function_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_call_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_parameters([NotNull] CastParser.Function_call_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] CastParser.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] CastParser.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_expression([NotNull] CastParser.Assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] CastParser.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_expression([NotNull] CastParser.Binary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CastParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] CastParser.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CastParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] CastParser.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_prototype([NotNull] CastParser.Function_prototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameters([NotNull] CastParser.Function_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.parameter_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declarator([NotNull] CastParser.Parameter_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declaration([NotNull] CastParser.Parameter_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.parameter_type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_type_specifier([NotNull] CastParser.Parameter_type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit_declarator_list([NotNull] CastParser.Init_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.single_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_declaration([NotNull] CastParser.Single_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.typeless_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeless_declaration([NotNull] CastParser.Typeless_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.fully_specified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFully_specified_type([NotNull] CastParser.Fully_specified_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.invariant_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvariant_qualifier([NotNull] CastParser.Invariant_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.interpolation_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolation_qualifier([NotNull] CastParser.Interpolation_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.layout_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier([NotNull] CastParser.Layout_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.layout_qualifier_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id_list([NotNull] CastParser.Layout_qualifier_id_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.layout_qualifier_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id([NotNull] CastParser.Layout_qualifier_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.precise_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecise_qualifier([NotNull] CastParser.Precise_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_qualifier([NotNull] CastParser.Type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.single_type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_type_qualifier([NotNull] CastParser.Single_type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.storage_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_qualifier([NotNull] CastParser.Storage_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.type_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name_list([NotNull] CastParser.Type_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] CastParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier([NotNull] CastParser.Type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_specifier([NotNull] CastParser.Array_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension([NotNull] CastParser.DimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.type_specifier_nonarray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier_nonarray([NotNull] CastParser.Type_specifier_nonarrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.precision_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecision_qualifier([NotNull] CastParser.Precision_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.struct_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_specifier([NotNull] CastParser.Struct_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.struct_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration_list([NotNull] CastParser.Struct_declaration_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration([NotNull] CastParser.Struct_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator_list([NotNull] CastParser.Struct_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator([NotNull] CastParser.Struct_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CastParser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_list([NotNull] CastParser.Initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.declaration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_statement([NotNull] CastParser.Declaration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CastParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.simple_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_statement([NotNull] CastParser.Simple_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement([NotNull] CastParser.Compound_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_no_new_scope([NotNull] CastParser.Statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.compound_statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement_no_new_scope([NotNull] CastParser.Compound_statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] CastParser.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] CastParser.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_statement([NotNull] CastParser.Selection_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.selection_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_rest_statement([NotNull] CastParser.Selection_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CastParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] CastParser.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_label([NotNull] CastParser.Case_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_statement([NotNull] CastParser.Iteration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.for_init_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_init_statement([NotNull] CastParser.For_init_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.for_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_rest_statement([NotNull] CastParser.For_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_statement([NotNull] CastParser.Jump_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_declaration([NotNull] CastParser.External_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CastParser.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] CastParser.Function_definitionContext context);
}
} // namespace Cast.Compiler
